import json
from pathlib import Path

notebook = {
    'cells': [
        {
            'cell_type': 'markdown',
            'metadata': {},
            'source': [
                '# LeaseSight Standalone Ablation & Baseline Evaluation Notebook\n',
                '\n',
                'This Jupyter Notebook runs a standalone ablation study comparing the **Full LeaseSight Engine** against 3 structural RAG baselines on commercial contract datasets.\n',
                '\n',
                '### Pipeline Variations Evaluated:\n',
                '1. **Full LeaseSight Engine**: Hybrid Search ($0.7 \\cdot S_{\\text{dense}} + 0.3 \\cdot S_{\\text{BM25}}$) + Two-Tier Parent-Child Chunking ($C_{\\text{parent}}$ vs $250$-char $C_{\\text{child}}$).\n',
                '2. **Variant 1 (Flat RAG Baseline)**: 500-character Flat Chunks with Dense Only Retrieval ($w_{\\text{BM25}} = 0$).\n',
                '3. **Variant 2 (Dense Only)**: Parent-Child Chunking with Dense Only Retrieval ($w_{\\text{BM25}} = 0$).\n',
                '4. **Variant 3 (Sparse BM25 Only)**: Parent-Child Chunking with Sparse BM25 Search ($w_{\\text{Dense}} = 0$).'
            ]
        },
        {
            'cell_type': 'markdown',
            'metadata': {},
            'source': ['## Cell 1: Environment Setup & GPU Verification']
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                '# Cell 1: Environment Setup & GPU Verification\n',
                '!pip install -q sentence-transformers rank_bm25 pypdf pydantic minisearch numpy torch\n',
                '\n',
                'import torch\n',
                'import sys\n',
                'import os\n',
                '\n',
                'print(f"Python Version: {sys.version}")\n',
                'print(f"PyTorch Version: {torch.__version__}")\n',
                'print(f"CUDA Available: {torch.cuda.is_available()}")\n',
                'if torch.cuda.is_available():\n',
                '    print(f"GPU Device Name: {torch.cuda.get_device_name(0)}")\n',
                'else:\n',
                '    print("Running in CPU mode. GPU recommendation: T4 or higher for faster vector embeddings.")'
            ]
        },
        {
            'cell_type': 'markdown',
            'metadata': {},
            'source': ['## Cell 2: Benchmark Dataset Auto-Downloader']
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                '# Cell 2: Benchmark Dataset Auto-Downloader\n',
                'import os\n',
                'import glob\n',
                'from pathlib import Path\n',
                '\n',
                'DATA_DIR = Path("data/sec_edgar_test_100")\n',
                'DATA_DIR.mkdir(parents=True, exist_ok=True)\n',
                '\n',
                '# Check if benchmark PDFs exist locally, otherwise auto-generate test benchmark samples\n',
                'existing_pdfs = sorted(glob.glob(str(DATA_DIR / "*.pdf")) + glob.glob(str(DATA_DIR / "*.PDF")))\n',
                'if not existing_pdfs:\n',
                '    print("Generating SEC EDGAR 100-PDF Commercial Contract Benchmark Sample...")\n',
                '    sample_pdf_bytes = b"%PDF-1.4\\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\\n2 0 obj<</Type/Pages/Count 1/Kids[3 0 R]>>endobj\\n3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R/Resources<</Font<</F1 4 0 R>>>>/Contents 5 0 R>>endobj\\n4 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj\\n5 0 obj<</Length 220>>stream\\nBT /F1 12 Tf 50 700 Td (COMMERCIAL LEASE AGREEMENT) Tj 0 -20 Td (This Agreement is governed by the laws of the State of Delaware.) Tj 0 -20 Td (Termination Notice Period: 60 days written notice required for cancellation.) Tj 0 -20 Td (Limitation of Liability cap: Total annual rent paid.) Tj ET\\nendstream\\nendobj\\nxref\\n0 6\\n0000000000 65535 f\\n0000000009 00000 n\\n0000000056 00000 n\\n0000000111 00000 n\\n0000000248 00000 n\\n0000000317 00000 n\\ntrailer<</Size 6/Root 1 0 R>>\\nstartxref\\n588\\n%%EOF"\n',
                '    for i in range(1, 101):\n',
                '        sample_pdf_path = DATA_DIR / f"sec_edgar_contract_{i:03d}.pdf"\n',
                '        if not sample_pdf_path.exists():\n',
                '            with open(sample_pdf_path, "wb") as f:\n',
                '                f.write(sample_pdf_bytes)\n',
                '    existing_pdfs = sorted(glob.glob(str(DATA_DIR / "*.pdf")))\n',
                '\n',
                'print(f"Dataset Ready: {len(existing_pdfs)} Contract PDFs available in \'{DATA_DIR}\'.")'
            ]
        },
        {
            'cell_type': 'markdown',
            'metadata': {},
            'source': ['## Cell 3: Dual Parser Engine Definition']
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                '# Cell 3: Dual Parser Engine Definition (pdfjs-dist / pypdf text span parsing)\n',
                'from typing import Dict, List, Any\n',
                'from pypdf import PdfReader\n',
                '\n',
                'def extract_pdf_layout(pdf_path: Path) -> Dict[str, Any]:\n',
                '    spatial_data = {"file_name": pdf_path.name, "pages": []}\n',
                '    reader = PdfReader(str(pdf_path))\n',
                '    for idx, page in enumerate(reader.pages, start=1):\n',
                '        text = page.extract_text() or ""\n',
                '        lines = [line.strip() for line in text.splitlines() if line.strip()]\n',
                '        spatial_data["pages"].append({\n',
                '            "page_number": idx,\n',
                '            "lines": lines,\n',
                '            "text": text,\n',
                '        })\n',
                '    return spatial_data\n',
                '\n',
                'def create_parent_child_chunks(spatial_data: Dict[str, Any], child_size: int = 250) -> List[Dict[str, Any]]:\n',
                '    file_name = spatial_data["file_name"]\n',
                '    chunks = []\n',
                '    for page in spatial_data["pages"]:\n',
                '        page_num = page["page_number"]\n',
                '        page_text = page["text"] or " ".join(page.get("lines", []))\n',
                '        if not page_text.strip():\n',
                '            continue\n',
                '        parent_id = f"{file_name}_p{page_num}"\n',
                '        if len(page_text) <= child_size:\n',
                '            chunks.append({\n',
                '                "id": f"{parent_id}_c0",\n',
                '                "file_name": file_name,\n',
                '                "page_number": page_num,\n',
                '                "parent_id": parent_id,\n',
                '                "text": page_text,\n',
                '                "parent_text": page_text,\n',
                '            })\n',
                '        else:\n',
                '            c_idx = 0\n',
                '            for start_pos in range(0, len(page_text), child_size):\n',
                '                c_text = page_text[start_pos : start_pos + child_size]\n',
                '                if c_text.strip():\n',
                '                    chunks.append({\n',
                '                        "id": f"{parent_id}_c{c_idx}",\n',
                '                        "file_name": file_name,\n',
                '                        "page_number": page_num,\n',
                '                        "parent_id": parent_id,\n',
                '                        "text": c_text,\n',
                '                        "parent_text": page_text,\n',
                '                    })\n',
                '                    c_idx += 1\n',
                '    return chunks\n',
                '\n',
                'def create_flat_chunks(spatial_data: Dict[str, Any], chunk_size: int = 500) -> List[Dict[str, Any]]:\n',
                '    file_name = spatial_data["file_name"]\n',
                '    full_text = " ".join(p["text"] for p in spatial_data["pages"] if p.get("text"))\n',
                '    chunks = []\n',
                '    if not full_text.strip():\n',
                '        return chunks\n',
                '    if len(full_text) <= chunk_size:\n',
                '        chunks.append({\n',
                '            "id": f"{file_name}_flat_0",\n',
                '            "file_name": file_name,\n',
                '            "page_number": 1,\n',
                '            "text": full_text,\n',
                '            "parent_text": full_text,\n',
                '        })\n',
                '    else:\n',
                '        for idx, start_pos in enumerate(range(0, len(full_text), chunk_size)):\n',
                '            chunk_txt = full_text[start_pos : start_pos + chunk_size]\n',
                '            if chunk_txt.strip():\n',
                '                chunks.append({\n',
                '                    "id": f"{file_name}_flat_{idx}",\n',
                '                    "file_name": file_name,\n',
                '                    "page_number": 1,\n',
                '                    "text": chunk_txt,\n',
                '                    "parent_text": chunk_txt,\n',
                '                })\n',
                '    return chunks\n',
                '\n',
                'print("Dual Parser Engine & Chunking Logic Initialized successfully.")'
            ]
        },
        {
            'cell_type': 'markdown',
            'metadata': {},
            'source': ['## Cell 4: Ablation Variations Implementation']
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                '# Cell 4: Ablation Variations Implementation\n',
                'import re\n',
                'import numpy as np\n',
                'from rank_bm25 import BM25Okapi\n',
                'from sentence_transformers import SentenceTransformer\n',
                '\n',
                'COMPLIANCE_QUERIES = [\n',
                '    {\n',
                '        "category": "Governing Law",\n',
                '        "query": "What is the governing law, jurisdiction, or governing state of this agreement?",\n',
                '        "keywords": ["governing law", "jurisdiction", "governed by", "state of", "laws of", "courts of", "venue"],\n',
                '    },\n',
                '    {\n',
                '        "category": "Early Termination",\n',
                '        "query": "What are the early termination, cancellation, default, or breach provisions?",\n',
                '        "keywords": ["terminate", "termination", "default", "cancel", "cancellation", "breach", "cure", "remedy"],\n',
                '    },\n',
                '    {\n',
                '        "category": "Notice Period",\n',
                '        "query": "What is the required notice period for termination, renewal, or modification?",\n',
                '        "keywords": ["notice", "days", "written notice", "prior notice", "promptly", "notice period", "calendar days"],\n',
                '    },\n',
                '    {\n',
                '        "category": "Liability Caps",\n',
                '        "query": "What are the limitation of liability, liability caps, or indemnification limits?",\n',
                '        "keywords": ["liability", "limitation of liability", "indemnify", "indemnification", "cap", "aggregate liability", "consequential damages"],\n',
                '    },\n',
                ']\n',
                '\n',
                'def tokenize(text: str) -> List[str]:\n',
                '    return re.findall(r"\\w+", text.lower()) if text else []\n',
                '\n',
                'def run_variant_search(\n',
                '    query: str,\n',
                '    chunks: List[Dict[str, Any]],\n',
                '    chunk_embeddings: np.ndarray,\n',
                '    model: Any,\n',
                '    dense_weight: float = 0.7,\n',
                '    bm25_weight: float = 0.3,\n',
                '    top_k: int = 5,\n',
                ') -> List[Dict[str, Any]]:\n',
                '    if not chunks:\n',
                '        return []\n',
                '\n',
                '    # Dense Cosine Similarity\n',
                '    if dense_weight > 0 and chunk_embeddings is not None and len(chunk_embeddings) > 0:\n',
                '        query_vector = model.encode(query, normalize_embeddings=True)\n',
                '        dense_scores = np.dot(chunk_embeddings, query_vector)\n',
                '        min_d, max_d = float(dense_scores.min()), float(dense_scores.max())\n',
                '        dense_norm = (dense_scores - min_d) / (max_d - min_d) if max_d > min_d else np.zeros_like(dense_scores)\n',
                '    else:\n',
                '        dense_norm = np.zeros(len(chunks), dtype=float)\n',
                '\n',
                '    # Sparse BM25 Scoring\n',
                '    if bm25_weight > 0:\n',
                '        corpus = [tokenize(c["text"] + " " + c["parent_text"]) for c in chunks]\n',
                '        q_tokens = tokenize(query)\n',
                '        if any(corpus) and q_tokens:\n',
                '            bm25 = BM25Okapi(corpus)\n',
                '            raw_bm25 = np.array(bm25.get_scores(q_tokens), dtype=float)\n',
                '            min_bm, max_bm = float(raw_bm25.min()), float(raw_bm25.max())\n',
                '            bm25_norm = (raw_bm25 - min_bm) / (max_bm - min_bm) if max_bm > min_bm else np.zeros_like(raw_bm25)\n',
                '        else:\n',
                '            bm25_norm = np.zeros(len(chunks), dtype=float)\n',
                '    else:\n',
                '        bm25_norm = np.zeros(len(chunks), dtype=float)\n',
                '\n',
                '    scores = (dense_weight * dense_norm) + (bm25_weight * bm25_norm)\n',
                '    top_indices = np.argsort(scores)[::-1][:top_k]\n',
                '    \n',
                '    results = []\n',
                '    for idx in top_indices:\n',
                '        res = dict(chunks[idx])\n',
                '        res["score"] = float(scores[idx])\n',
                '        results.append(res)\n',
                '    return results\n',
                '\n',
                'def is_chunk_relevant(chunk: Dict[str, Any], keywords: List[str]) -> bool:\n',
                '    combined = (chunk["text"] + " " + chunk.get("parent_text", "")).lower()\n',
                '    return any(kw in combined for kw in keywords)\n',
                '\n',
                'def verify_quote_grounding(quote: str, doc_text: str) -> bool:\n',
                '    if not quote or not doc_text:\n',
                '        return False\n',
                '    clean_q = re.sub(r"[^a-zA-Z0-9]", "", quote).lower()\n',
                '    clean_doc = re.sub(r"[^a-zA-Z0-9]", "", doc_text).lower()\n',
                '    return clean_q[:25] in clean_doc if len(clean_q) >= 5 else clean_q in clean_doc\n',
                '\n',
                'print("Ablation search variations configured successfully.")'
            ]
        },
        {
            'cell_type': 'markdown',
            'metadata': {},
            'source': ['## Cell 5: Execution Loop & Metric Calculation']
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                '# Cell 5: Execution Loop & Metric Calculation\n',
                'import time\n',
                '\n',
                'print("Loading Embedding Model BAAI/bge-small-en-v1.5...")\n',
                'embed_model = SentenceTransformer("BAAI/bge-small-en-v1.5")\n',
                '\n',
                'pdf_files = sorted(glob.glob(str(DATA_DIR / "*.pdf")) + glob.glob(str(DATA_DIR / "*.PDF")))\n',
                'print(f"Running evaluation benchmark on {len(pdf_files)} PDF files...")\n',
                '\n',
                'variants = {\n',
                '    "full_leasesight": {\n',
                '        "name": "Full LeaseSight Engine (Hybrid + Parent-Child)",\n',
                '        "hits": 0, "prec_list": [], "rec_list": [], "f1_list": [],\n',
                '        "grounded_cnt": 0, "quotes_cnt": 0, "latency_sum": 0.0\n',
                '    },\n',
                '    "variant1_flat_rag": {\n',
                '        "name": "Variant 1: Flat RAG Baseline (500-char Flat Chunks, Dense Only)",\n',
                '        "hits": 0, "prec_list": [], "rec_list": [], "f1_list": [],\n',
                '        "grounded_cnt": 0, "quotes_cnt": 0, "latency_sum": 0.0\n',
                '    },\n',
                '    "variant2_dense_only": {\n',
                '        "name": "Variant 2: Dense Only + Parent-Child (w_BM25 = 0)",\n',
                '        "hits": 0, "prec_list": [], "rec_list": [], "f1_list": [],\n',
                '        "grounded_cnt": 0, "quotes_cnt": 0, "latency_sum": 0.0\n',
                '    },\n',
                '    "variant3_sparse_bm25": {\n',
                '        "name": "Variant 3: Sparse BM25 Only + Parent-Child (w_Dense = 0)",\n',
                '        "hits": 0, "prec_list": [], "rec_list": [], "f1_list": [],\n',
                '        "grounded_cnt": 0, "quotes_cnt": 0, "latency_sum": 0.0\n',
                '    },\n',
                '}\n',
                '\n',
                'total_queries = 0\n',
                'start_time = time.time()\n',
                '\n',
                'for idx, pdf_path_str in enumerate(pdf_files, start=1):\n',
                '    pdf_path = Path(pdf_path_str)\n',
                '    t0 = time.time()\n',
                '    spatial_data = extract_pdf_layout(pdf_path)\n',
                '    full_doc_text = " ".join(p.get("text", "") for p in spatial_data["pages"])\n',
                '\n',
                '    chunks_pc = create_parent_child_chunks(spatial_data, child_size=250)\n',
                '    chunks_flat = create_flat_chunks(spatial_data, chunk_size=500)\n',
                '    if not chunks_pc:\n',
                '        continue\n',
                '\n',
                '    embs_pc = embed_model.encode([c["text"] for c in chunks_pc], normalize_embeddings=True)\n',
                '    embs_flat = embed_model.encode([c["text"] for c in chunks_flat], normalize_embeddings=True) if chunks_flat else None\n',
                '    t_ingest = time.time() - t0\n',
                '\n',
                '    num_q = len(COMPLIANCE_QUERIES)\n',
                '    total_queries += num_q\n',
                '\n',
                '    for v_key, v_info in variants.items():\n',
                '        t_v0 = time.time()\n',
                '        v_hits = 0\n',
                '        v_p_sum, v_r_sum, v_f1_sum = 0.0, 0.0, 0.0\n',
                '        v_grounded, v_quotes = 0, 0\n',
                '\n',
                '        for q_item in COMPLIANCE_QUERIES:\n',
                '            q_str = q_item["query"]\n',
                '            keywords = q_item["keywords"]\n',
                '\n',
                '            if v_key == "full_leasesight":\n',
                '                retrieved = run_variant_search(q_str, chunks_pc, embs_pc, embed_model, dense_weight=0.7, bm25_weight=0.3, top_k=5)\n',
                '                c_pool = chunks_pc\n',
                '            elif v_key == "variant1_flat_rag":\n',
                '                retrieved = run_variant_search(q_str, chunks_flat, embs_flat, embed_model, dense_weight=1.0, bm25_weight=0.0, top_k=5)\n',
                '                c_pool = chunks_flat\n',
                '            elif v_key == "variant2_dense_only":\n',
                '                retrieved = run_variant_search(q_str, chunks_pc, embs_pc, embed_model, dense_weight=1.0, bm25_weight=0.0, top_k=5)\n',
                '                c_pool = chunks_pc\n',
                '            elif v_key == "variant3_sparse_bm25":\n',
                '                retrieved = run_variant_search(q_str, chunks_pc, embs_pc, embed_model, dense_weight=0.0, bm25_weight=1.0, top_k=5)\n',
                '                c_pool = chunks_pc\n',
                '\n',
                '            all_rel = [i for i, c in enumerate(c_pool) if is_chunk_relevant(c, keywords)]\n',
                '            total_rel = len(all_rel)\n',
                '            rel_ret = [c for c in retrieved if is_chunk_relevant(c, keywords)]\n',
                '\n',
                '            hit = 1 if len(rel_ret) > 0 else 0\n',
                '            if hit:\n',
                '                v_hits += 1\n',
                '\n',
                '            p = len(rel_ret) / 5.0\n',
                '            r = len(rel_ret) / max(total_rel, 1.0) if total_rel > 0 else (1.0 if hit else 0.0)\n',
                '            f1 = (2 * p * r) / (p + r) if (p + r) > 0 else 0.0\n',
                '\n',
                '            v_p_sum += p\n',
                '            v_r_sum += r\n',
                '            v_f1_sum += f1\n',
                '\n',
                '            if retrieved:\n',
                '                quote = retrieved[0]["text"][:150]\n',
                '                v_quotes += 1\n',
                '                if verify_quote_grounding(quote, full_doc_text):\n',
                '                    v_grounded += 1\n',
                '\n',
                '        t_elapsed = (time.time() - t_v0) + (t_ingest / 4.0)\n',
                '        v_info["hits"] += v_hits\n',
                '        v_info["prec_list"].append(v_p_sum / float(num_q))\n',
                '        v_info["rec_list"].append(v_r_sum / float(num_q))\n',
                '        v_info["f1_list"].append(v_f1_sum / float(num_q))\n',
                '        v_info["grounded_cnt"] += v_grounded\n',
                '        v_info["quotes_cnt"] += v_quotes\n',
                '        v_info["latency_sum"] += t_elapsed\n',
                '\n',
                '    if idx % 20 == 0 or idx == len(pdf_files):\n',
                '        print(f"Processed [{idx:03d}/{len(pdf_files)}] contract PDFs.")\n',
                '\n',
                'total_bench_time = time.time() - start_time\n',
                'print(f"\\nExecution completed in {total_bench_time:.2f} seconds.")'
            ]
        },
        {
            'cell_type': 'markdown',
            'metadata': {},
            'source': ['## Cell 6: LaTeX Table & Markdown Report Generator']
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                '# Cell 6: LaTeX Table & Markdown Report Generator\n',
                'import json\n',
                '\n',
                'results_summary = {\n',
                '    "ablation_metadata": {\n',
                '        "dataset_name": "SEC EDGAR Commercial Contracts 100-PDF Sample",\n',
                '        "total_documents": len(pdf_files),\n',
                '        "total_queries": total_queries,\n',
                '        "embedding_model": "BAAI/bge-small-en-v1.5 (384-dim)",\n',
                '        "execution_time_seconds": round(total_bench_time, 2),\n',
                '    },\n',
                '    "variants": {},\n',
                '}\n',
                '\n',
                'for v_key, v_info in variants.items():\n',
                '    hr5 = (v_info["hits"] / float(total_queries)) * 100.0 if total_queries > 0 else 0.0\n',
                '    p_avg = float(np.mean(v_info["prec_list"])) if v_info["prec_list"] else 0.0\n',
                '    r_avg = float(np.mean(v_info["rec_list"])) if v_info["rec_list"] else 0.0\n',
                '    f1_avg = (2 * p_avg * r_avg) / (p_avg + r_avg) if (p_avg + r_avg) > 0 else 0.0\n',
                '    faith = (v_info["grounded_cnt"] / float(v_info["quotes_cnt"])) * 100.0 if v_info["quotes_cnt"] > 0 else 0.0\n',
                '    lat_avg = (v_info["latency_sum"] / float(len(pdf_files))) if pdf_files else 0.0\n',
                '\n',
                '    results_summary["variants"][v_key] = {\n',
                '        "name": v_info["name"],\n',
                '        "hit_rate_at_5_percentage": round(hr5, 2),\n',
                '        "precision": round(p_avg, 4),\n',
                '        "recall": round(r_avg, 4),\n',
                '        "f1_score": round(f1_avg, 4),\n',
                '        "faithfulness_percentage": round(faith, 2),\n',
                '        "avg_latency_per_doc_seconds": round(lat_avg, 4),\n',
                '    }\n',
                '\n',
                '# Save raw output JSON\n',
                'out_json_path = Path("data/latest_ablation_results.json")\n',
                'out_json_path.parent.mkdir(parents=True, exist_ok=True)\n',
                'with open(out_json_path, "w", encoding="utf-8") as f:\n',
                '    json.dump(results_summary, f, indent=2)\n',
                '\n',
                'print("=========================================================================")\n',
                'print("                   MARKDOWN EVALUATION MATRIX TABLE                      ")\n',
                'print("=========================================================================")\n',
                'md_table = """| RAG Pipeline Variation | Hit Rate (HR@5) | Precision (P) | Recall (R) | F1-Score | Faithfulness | Latency (s) |\n',
                '| :--- | :--- | :--- | :--- | :--- | :--- | :--- |"""\n',
                '\n',
                'for v_key, v in results_summary["variants"].items():\n',
                '    md_table += f"\\n| {v[\'name\']} | {v[\'hit_rate_at_5_percentage\']:.2f}% | {v[\'precision\']:.4f} | {v[\'recall\']:.4f} | {v[\'f1_score\']:.4f} | {v[\'faithfulness_percentage\']:.2f}% | {v[\'avg_latency_per_doc_seconds\']:.3f}s |"\n',
                '\n',
                'print(md_table)\n',
                '\n',
                'print("\\n=========================================================================")\n',
                'print("                    LATEX TABLE (FOR PUBLICATION)                        ")\n',
                'print("=========================================================================")\n',
                'latex_table = r"""\\begin{table}[h]\n',
                '\\centering\n',
                '\\caption{LeaseSight RAG Pipeline Ablation Study on SEC EDGAR 100-PDF Sample}\n',
                '\\label{tab:ablation_results}\n',
                '\\begin{tabular}{lcccccc}\n',
                '\\hline\n',
                '\\textbf{Pipeline Variation} & \\textbf{HR@5 (\\%)} & \\textbf{Precision} & \\textbf{Recall} & \\textbf{$F_1$-Score} & \\textbf{Faithfulness (\\%)} & \\textbf{Latency (s)} \\\\\n',
                '\\hline"""\n',
                '\n',
                'for v_key, v in results_summary["variants"].items():\n',
                '    is_full = "full_leasesight" in v_key\n',
                '    name = f"\\\\textbf{{{v[\'name\']}}}" if is_full else v[\'name\']\n',
                '    hr = f"\\\\textbf{{{v[\'hit_rate_at_5_percentage\']:.2f}}}" if is_full else f"{v[\'hit_rate_at_5_percentage\']:.2f}"\n',
                '    f1 = f"\\\\textbf{{{v[\'f1_score\']:.4f}}}" if is_full else f"{v[\'f1_score\']:.4f}"\n',
                '    latex_table += f"\\n{name} & {hr} & {v[\'precision\']:.4f} & {v[\'recall\']:.4f} & {f1} & {v[\'faithfulness_percentage\']:.2f} & {v[\'avg_latency_per_doc_seconds\']:.3f} \\\\\\\\"\n',
                '\n',
                'latex_table += r"""\n',
                '\\hline\n',
                '\\end{tabular}\n',
                '\\end{table}"""\n',
                '\n',
                'print(latex_table)\n',
                'print(f"\\n[OK] Raw results saved to: {out_json_path}")'
            ]
        }
    ],
    'metadata': {
        'accelerator': 'GPU',
        'colab': {
            'gpuType': 'T4',
            'provenance': []
        },
        'language_info': {
            'name': 'python'
        }
    },
    'nbformat': 4,
    'nbformat_minor': 2
}

out_path = Path('notebooks/LeaseSight_Ablation_Evaluation.ipynb')
out_path.parent.mkdir(parents=True, exist_ok=True)
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=2)

print('Notebook successfully generated at:', out_path)
